M.11_Lab Activity 4
Instructions

Go through the notebooks Lesson_4_lab_data_processing.ipynb in Google Colab or Jupyter. Remember to clone a version, rename appropriately and save a copy in your google drive. You can remove the outputs from each cell and walk through each cell of the codes to understand what is going on in the program. Each of the three aspects mentioned above contains notes and explanations. Remember to push your code into a repository created in GitHub to demonstrate your understanding of version control. Make at least 3 commits while making changes to your code.

Complete the following tasks. These are mapped to the sections in the notebook.

- Data manipulation and processing
1. Create dataframe using Pandas
2. Perform row level manipulations such as drop rows and columns
3. Fill in Null values
4. GroupBy and use Describe for dataframe
5. Concatenation and Merging dataframes

In [2]:
# import libraries

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [7]:
#1. Create a df using pandas
df= pd.DataFrame({'A':[1, 2, np.nan, 10], 'B': [5, np.nan, np.nan,6], 'C':[1,2,3,4]})
df['States']= 'CA FL CH ST'.split()
df.set_index('States', inplace=True)
print(df)

           A    B  C
States
CA       1.0  5.0  1
FL       2.0  NaN  2
CH       NaN  NaN  3
ST      10.0  6.0  4

In [8]:
#2. Perform row level manipulations such as drop rows and columns
print('\nDropping any rows with a NaN value\n', '-'*35, sep="")
print(df.dropna(axis=0))

Dropping any rows with a NaN value
-----------------------------------
           A    B  C
States
CA       1.0  5.0  1
ST      10.0  6.0  4

In [9]:
print("\nDropping any column with a NaN value\n",'-'*35, sep='')
print(df.dropna(axis=1))

Dropping any column with a NaN value
-----------------------------------
        C
States
CA      1
FL      2
CH      3
ST      4

In [14]:
print('\nDropping a row with a minimun 2 NaN value using thresh parameter\n','-'*68, sep='')
print(df.dropna(axis=0, thresh=4))

Dropping a row with a minimun 2 NaN value using thresh parameter
--------------------------------------------------------------------
Empty DataFrame
Columns: [A, B, C]
Index: []

In [21]:
#3. Fill in Null values
print('\nFilling values with default value\n','-'*35,sep='')
print(df.fillna(value= 'N/A'))

Filling values with default value
-----------------------------------
           A    B  C
States
CA       1.0  5.0  1
FL       2.0  N/A  2
CH       N/A  N/A  3
ST      10.0  6.0  4

In [26]:
print("\nFilling values with a computed value (mean of column A here)\n",'-'*60, sep='')
print(df.fillna(value=round(df['A'].mean(),1)))

Filling values with a computed value (mean of column A here)
------------------------------------------------------------
           A    B  C
States
CA       1.0  5.0  1
FL       2.0  4.3  2
CH       4.3  4.3  3
ST      10.0  6.0  4

In [28]:
#4. GroupBy and use Describe for dataframe
# 1. Create dataframe
data = {'Company':['Shell','7Guys','7&Eleven','Costco','Walmart','SuperStore'],
       'Person':['Marina','Giovy','Gladys','Antonio','Joaquin','Javiera'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
df

      Company   Person  Sales
0       Shell   Marina    200
1       7Guys    Giovy    120
2    7&Eleven   Gladys    340
3      Costco  Antonio    124
4     Walmart  Joaquin    243
5  SuperStore  Javiera    350

In [40]:
#2. Group by sales company
companySales = (df.groupby('Company')['Sales'].mean())
print("\nGrouping by 'Company' column and listing mean sales\n",'-'*55, sep='')
print(companySales)

Grouping by 'Company' column and listing mean sales
-------------------------------------------------------
Company
7&Eleven      340.0
7Guys         120.0
Costco        124.0
Shell         200.0
SuperStore    350.0
Walmart       243.0
Name: Sales, dtype: float64

In [41]:
#sum sales by company
print("\nGrouping by 'Company' column and listing sum of sales\n",'-'*55, sep='')
print(companySales)

Grouping by 'Company' column and listing sum of sales
-------------------------------------------------------
Company
7&Eleven      340.0
7Guys         120.0
Costco        124.0
Shell         200.0
SuperStore    350.0
Walmart       243.0
Name: Sales, dtype: float64

In [47]:
#Statistics values
print("\nAll in one line of command (Stats for 'FB')\n",'-'*65, sep='')
print(df.groupby('Company').describe().loc[['Costco']])

All in one line of command (Stats for 'FB')
-----------------------------------------------------------------
        Sales
        count   mean std    min    25%    50%    75%    max
Company
Costco    1.0  124.0 NaN  124.0  124.0  124.0  124.0  124.0

In [48]:
print("\nSame type of extraction with little different command\n",'-'*68, sep='')
print(df.groupby('Company').describe().loc[['Shell', 'Walmart']])

Same type of extraction with little different command
--------------------------------------------------------------------
        Sales
        count   mean std    min    25%    50%    75%    max
Company
Shell     1.0  200.0 NaN  200.0  200.0  200.0  200.0  200.0
Walmart   1.0  243.0 NaN  243.0  243.0  243.0  243.0  243.0

In [49]:
#show all companies stats
print("\nShow all company stats\n",'-'*68, sep='')
print(df.groupby('Company').describe())

Show all company stats
--------------------------------------------------------------------
           Sales
           count   mean std    min    25%    50%    75%    max
Company
7&Eleven     1.0  340.0 NaN  340.0  340.0  340.0  340.0  340.0
7Guys        1.0  120.0 NaN  120.0  120.0  120.0  120.0  120.0
Costco       1.0  124.0 NaN  124.0  124.0  124.0  124.0  124.0
Shell        1.0  200.0 NaN  200.0  200.0  200.0  200.0  200.0
SuperStore   1.0  350.0 NaN  350.0  350.0  350.0  350.0  350.0
Walmart      1.0  243.0 NaN  243.0  243.0  243.0  243.0  243.0

In [72]:
#5. Concatenation and Merging dataframes
# Merging two data frames
# Creating data frames
df1 = pd.DataFrame({
                    'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[0, 1, 2, 3])              

print(df1)

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [73]:

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[0, 1, 2, 3]) 
print(df2)

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [78]:

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8,9,10,11])
print(df3)

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [75]:
print("\nThe DataFrame number 1\n",'-'*30, sep='')
print(df1)

The DataFrame number 1
------------------------------
    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [76]:
print("\nThe DataFrame number 2\n",'-'*30, sep='')
print(df2)

The DataFrame number 2
------------------------------
    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [79]:
print("\nThe DataFrame number 3\n",'-'*30, sep='')
print(df3)

The DataFrame number 3
------------------------------
      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [82]:
#concatenation
df_cat1 = pd.concat([df1,df2,df3], axis=0)
print("\nAfter concatenation along row\n",'-'*30, sep='')
print(df_cat1)
df_cat1.loc[2]

After concatenation along row
------------------------------
      A    B    C    D
0    A4   B4   C4   D4
1    A5   B5   C5   D5
2    A6   B6   C6   D6
3    A7   B7   C7   D7
0    A4   B4   C4   D4
1    A5   B5   C5   D5
2    A6   B6   C6   D6
3    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

    A   B   C   D
2  A6  B6  C6  D6
2  A6  B6  C6  D6

In [83]:
df_cat1.iloc[4]

A    A4
B    B4
C    C4
D    D4
Name: 0, dtype: str

In [84]:
df_cat2 = pd.concat([df1,df2,df3], axis=1)
print("\nAfter concatenation along column\n",'-'*60, sep='')
print(df_cat2)

After concatenation along column
------------------------------------------------------------
      A    B    C    D    A    B    C    D    A    B    C    D
0    A4   B4   C4   D4   A4   B4   C4   D4  NaN  NaN  NaN  NaN
1    A5   B5   C5   D5   A5   B5   C5   D5  NaN  NaN  NaN  NaN
2    A6   B6   C6   D6   A6   B6   C6   D6  NaN  NaN  NaN  NaN
3    A7   B7   C7   D7   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [88]:
df_cat2= df_cat2.fillna(0)
print("\nAfter filling missing values with zero\n",'-'*60, sep='')
print(df_cat2)

After filling missing values with zero
------------------------------------------------------------
     A   B   C   D   A   B   C   D    A    B    C    D
0   A4  B4  C4  D4  A4  B4  C4  D4    0    0    0    0
1   A5  B5  C5  D5  A5  B5  C5  D5    0    0    0    0
2   A6  B6  C6  D6  A6  B6  C6  D6    0    0    0    0
3   A7  B7  C7  D7  A7  B7  C7  D7    0    0    0    0
8    0   0   0   0   0   0   0   0   A8   B8   C8   D8
9    0   0   0   0   0   0   0   0   A9   B9   C9   D9
10   0   0   0   0   0   0   0   0  A10  B10  C10  D10
11   0   0   0   0   0   0   0   0  A11  B11  C11  D11

In [90]:
# Merging by a common key
left = pd.DataFrame({'key': ['K0', 'K8', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})
print(left, right)

  key   A   B
0  K0  A0  B0
1  K8  A1  B1
2  K2  A2  B2
3  K3  A3  B3   key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [91]:
print("\nThe DataFrame 'left'\n",'-'*30, sep='')
print(left)

The DataFrame 'left'
------------------------------
  key   A   B
0  K0  A0  B0
1  K8  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [92]:
print("\nThe DataFrame 'right'\n",'-'*30, sep='')
print(right)

The DataFrame 'right'
------------------------------
  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [93]:
merge1= pd.merge(left,right,how='inner',on='key')
print("\nAfter simple merging with 'inner' method\n",'-'*50, sep='')
print(merge1)

After simple merging with 'inner' method
--------------------------------------------------
  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K2  A2  B2  C2  D2
2  K3  A3  B3  C3  D3

In [95]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})
print(left, right)

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3   key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [96]:
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [99]:
#join operators
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])
print(left, right)

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2      C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [100]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [102]:
right.join(left, how='outer')

      C    D    A    B
K0   C0   D0   A0   B0
K1  NaN  NaN   A1   B1
K2   C2   D2   A2   B2
K3   C3   D3  NaN  NaN

In [103]:
#Use of apply fuctions
# Define a function
def testfunc(x):
    if (x> 300):
        return (10*np.log10(x))
    else:
        return (x/10)

In [104]:
df = pd.DataFrame({'col1':[1,2,3,4,5,6,7,8,9,10],
                   'col2':[444,555,666,444,333,222,666,777,666,555],
                   'col3':'aaa bb c dd eeee fff gg h iii j'.split()})
df

   col1  col2  col3
0     1   444   aaa
1     2   555    bb
2     3   666     c
3     4   444    dd
4     5   333  eeee
5     6   222   fff
6     7   666    gg
7     8   777     h
8     9   666   iii
9    10   555     j

In [105]:
df['FuncApplied'] = df['col2'].apply(lambda x : np.log(x))
print(df)

   col1  col2  col3  FuncApplied
0     1   444   aaa     6.095825
1     2   555    bb     6.318968
2     3   666     c     6.501290
3     4   444    dd     6.095825
4     5   333  eeee     5.808142
5     6   222   fff     5.402677
6     7   666    gg     6.501290
7     8   777     h     6.655440
8     9   666   iii     6.501290
9    10   555     j     6.318968

In [106]:
df['col3length']= df['col3'].apply(len)
print(df)

   col1  col2  col3  FuncApplied  col3length
0     1   444   aaa     6.095825           3
1     2   555    bb     6.318968           2
2     3   666     c     6.501290           1
3     4   444    dd     6.095825           2
4     5   333  eeee     5.808142           4
5     6   222   fff     5.402677           3
6     7   666    gg     6.501290           2
7     8   777     h     6.655440           1
8     9   666   iii     6.501290           3
9    10   555     j     6.318968           1

In [107]:
df['FuncApplied'].apply(lambda x: np.sqrt(x))

0    2.468972
1    2.513756
2    2.549763
3    2.468972
4    2.410009
5    2.324366
6    2.549763
7    2.579814
8    2.549763
9    2.513756
Name: FuncApplied, dtype: float64

In [108]:
print("\nSum of the column 'FuncApplied' is: ",df['FuncApplied'].sum())

Sum of the column 'FuncApplied' is:  62.19971458619886

In [109]:
print("Mean of the column 'FuncApplied' is: ",df['FuncApplied'].mean())

Mean of the column 'FuncApplied' is:  6.219971458619886

In [110]:
print("Std dev of the column 'FuncApplied' is: ",df['FuncApplied'].std())

Std dev of the column 'FuncApplied' is:  0.3822522801574853

In [111]:
print("Min and max of the column 'FuncApplied' are: ",df['FuncApplied'].min(),"and",df['FuncApplied'].max())

Min and max of the column 'FuncApplied' are:  5.402677381872279 and 6.655440350367647

In [112]:
#Deletion, sorting, list of column and row names
print("\nName of columns\n",'-'*20, sep='')
print(df.columns)

Name of columns
--------------------
Index(['col1', 'col2', 'col3', 'FuncApplied', 'col3length'], dtype='str')

In [113]:
l = list(df.columns)
print("\nColumn names in a list of strings for later manipulation:",l)

Column names in a list of strings for later manipulation: ['col1', 'col2', 'col3', 'FuncApplied', 'col3length']

In [114]:
print("\nDeleting last column by 'del' command\n",'-'*50, sep='')
del df['col3length']
print(df)
df['col3length']= df['col3'].apply(len)

Deleting last column by 'del' command
--------------------------------------------------
   col1  col2  col3  FuncApplied
0     1   444   aaa     6.095825
1     2   555    bb     6.318968
2     3   666     c     6.501290
3     4   444    dd     6.095825
4     5   333  eeee     5.808142
5     6   222   fff     5.402677
6     7   666    gg     6.501290
7     8   777     h     6.655440
8     9   666   iii     6.501290
9    10   555     j     6.318968

In [115]:
df.sort_values(by='col2') #inplace=False by default

   col1  col2  col3  FuncApplied  col3length
5     6   222   fff     5.402677           3
4     5   333  eeee     5.808142           4
0     1   444   aaa     6.095825           3
3     4   444    dd     6.095825           2
1     2   555    bb     6.318968           2
9    10   555     j     6.318968           1
6     7   666    gg     6.501290           2
2     3   666     c     6.501290           1
8     9   666   iii     6.501290           3
7     8   777     h     6.655440           1

In [116]:
df.sort_values(by='FuncApplied',ascending=False) #inplace=False by default

   col1  col2  col3  FuncApplied  col3length
7     8   777     h     6.655440           1
2     3   666     c     6.501290           1
6     7   666    gg     6.501290           2
8     9   666   iii     6.501290           3
9    10   555     j     6.318968           1
1     2   555    bb     6.318968           2
0     1   444   aaa     6.095825           3
3     4   444    dd     6.095825           2
4     5   333  eeee     5.808142           4
5     6   222   fff     5.402677           3

In [117]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[None,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [118]:
df.isnull()

    col1   col2   col3
0  False   True  False
1  False  False  False
2  False  False  False
3   True  False  False

In [119]:
df.fillna('FILL')

   col1   col2 col3
0   1.0   FILL  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3  FILL  444.0  xyz

In [120]:
df1

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [121]:
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [122]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [123]:
pd.merge(df1, df2, how='inner')

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [124]:
pd.merge(df1, df2, how='left')

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [125]:
pd.merge(df1, df2, how='right')

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

#%% md
## **Python container objects and functions** for data processing

In this session, we are going to learn the following key topics:
- Tuples
- Set
- Dictionary
- Function
- Lambda
- Iterator
- Generator
- Map
- Reduce
- Filter

#%% md
### Tuples

In Python, tuples are similar to lists but they are immutable i.e. they cannot be changed. You would use the tuples to present data that shouldn't be changed, such as days of week or dates on  a calendar.

In this section, we will get a brief overview of the following key topics:

    1.) Constructing Tuples
    2.) Basic Tuple Methods
    3.) Immutability
    4.) When to Use Tuples

You'll have an intuition of how to use tuples based on what you've learned about lists. But, Tuples work very similar to lists but the  major difference is tuples are immutable.

## Constructing Tuples

The construction of tuples use () with elements separated by commas where in the arguments will be passed within brackets. For example:

In [ ]:
# Can create a tuple with mixed types
t = (1,2,3)

In [ ]:
# Check len just like a list
type(t)

In [ ]:
# Check len just like a list
type(t)

In [ ]:
# Use indexing just like we did in lists
t[0]

In [ ]:
# Slicing just like a list
t[-1]

#%% md
#### Basic Tuple Methods

Tuples have built-in methods, but not as many as lists do. Let's see two samples of tuple built-in methods:

In [ ]:
# Use .index to enter a value and return the index
t.index(89)

In [ ]:
# Use .count to count the number of times a value appears
t.count('one')

#%% md
#### Immutability

As tuples are immutable, it can't be stressed enough and add more into it. To drive that point home:

In [ ]:
t[0]= 'change'

In [ ]:
##
Because tuple being immutable they can't grow. Once a tuple is made we can not add to it.

In [ ]:
t.append('nope')

#%% md
#### When to use Tuples

You may be wondering, "Why to bother using tuples when they have a few available methods?"

Tuples are not used often as lists in programming but are used when immutability is necessary. While you are passing around an object and if you need to make sure that it does not get changed then tuple become your solution. It provides a convenient source of data integrity.

You should now be able to create and use tuples in your programming as well as have a complete understanding of their immutability.

In [ ]:
#%% md
### Sets

Sets are an unordered collection of *unique* elements which can be constructed using the set() function.

Let's go ahead and create a set to see how it works.

In [ ]:
x = set()

In [ ]:
# We add to sets with the add() method
x.add(3)

In [ ]:
#Show
x

#%% md
Note that the curly brackets do not indicate a dictionary! Using only keys, you can draw analogies as a set being a dictionary.

We know that a set has an only unique entry. Now, let us see what happens when we try to add something more that is already present in a set?

In [ ]:
# Add a different element
x.add(2)

In [ ]:
#Show
x

In [ ]:
# Try to add the same element
x.add(1)

In [ ]:
#Show
x

#%% md
Notice, how it won't place another 1 there as a set is only concerned with unique elements! However, We can cast a list with multiple repeat elements to a set to get the unique elements. For example:

In [ ]:
# Create a list with repeats
l = [1,1,2,2,3,4,5,6,1,1]

In [ ]:
# Cast as set to get unique values
set(l)